source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

inhibit_all_warnings!

target 'YQTest' do
    pod 'AFNetworking'
    pod 'Reachability'
    pod 'SDWebImage'
    pod 'YYModel'
    pod 'YYText'
    pod 'MJRefresh'
    pod 'IQKeyboardManager'
    pod 'MBProgressHUD'
    pod 'Masonry'
    pod 'JKCountDownButton'
    pod 'TZImagePickerController'
    

end
